const BINS={food_waste:{name:'Food waste',color:'#25884a',emoji:'🥬'},general_waste:{name:'General waste',color:'#626b70',emoji:'🗑️'},recyclables:{name:'Recyclables',color:'#2874c8',emoji:'♻️'},drain:{name:'Drain',color:'#58acd2',emoji:'💧'}};
const ITEMS=[['Rice','🍚','food_waste'],['Noodles','🍜','food_waste'],['Veg scraps','🥬','food_waste'],['Bones','🦴','food_waste'],['Eggshells','🥚','food_waste'],['Fruit peel','🍌','food_waste'],['Tissue','🧻','general_waste'],['Plastic spoon','🥄','general_waste'],['Sauce packet','🫙','general_waste'],['Wrapper','🍬','general_waste'],['Straw','🥤','general_waste'],['Disposable cup','🥤','general_waste'],['Soup / drink','🥣','drain'],['Clean plastic bottle','🧴','recyclables'],['Clean can','🥫','recyclables']].map(([name,emoji,bin])=>({name,emoji,bin}));
const DEMOS=[{is_food_tray:true,items:[['Leftover rice','food_waste','high'],['Chicken bones','food_waste','medium'],['Plastic spoon','general_waste','high'],['Sauce packet','general_waste','high'],['Soup','drain','high']],tip:'Empty liquids first so the food scraps stay compostable.'},{is_food_tray:true,items:[['Noodle scraps','food_waste','high'],['Used tissue','general_waste','medium'],['Clean plastic bottle','recyclables','medium'],['Vegetable scraps','food_waste','high']],tip:'Tissues go in General Waste at SUSS.'},{is_food_tray:true,items:[['Fruit peel','food_waste','high'],['Disposable cup','general_waste','medium'],['Drink left in cup','drain','medium'],['Clean can','recyclables','high']],tip:'Pour the drink away before sorting the cup.'}].map(x=>({...x,items:x.items.map(([name,bin,confidence])=>({name,bin,confidence}))}));
const QUESTIONS=[['Can tissues go in food waste at SUSS?',['Yes','No'],1,'Tissues belong in General Waste.'],['What should you do with soup first?',['Pour it into the drain','Put it in food waste'],0,'Liquids go down the drain first.'],['Which bottle can be recycled?',['A clean plastic bottle','A food-soiled bottle'],0,'Only clean plastic bottles and clean cans go in recycling.'],['Where do rice and noodles go?',['General Waste','Food Waste'],1,'Cooked food scraps can be composted.'],['Where do plastic spoons go?',['Food Waste','General Waste'],1,'Plastic cutlery contaminates food waste.']];
const $=(s,r=document)=>r.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dayKey=v=>{const d=new Date(v);return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`};
const offset=n=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return d.toISOString()};
let ledger=[{id:'a',date:offset(-3),description:'First scan bonus',points:20},{id:'b',date:offset(-3),description:'Completed scan',points:15},{id:'c',date:offset(-2),description:'Completed scan',points:15},{id:'d',date:offset(-1),description:'Completed scan',points:15},{id:'e',date:offset(-1),description:'3-day streak bonus',points:10},{id:'f',date:offset(0),description:'Games · Sort Rush',points:10}];
let vouchers=[],demo=false,tab='scan',flow=null,modal=null,game=null,best={rush:0,spot:0,quiz:0},outlet=new URLSearchParams(location.search).get('outlet')||'SUSS campus outlet',nickname='Eco-loop friend',totalSorts=3,toastTimer;
const balance=()=>ledger.reduce((n,x)=>n+x.points,0),add=(description,points)=>{if(points)ledger.push({id:crypto.randomUUID?.()||String(Date.now()+Math.random()),date:new Date().toISOString(),description,points})};
const sortEntries=()=>ledger.filter(x=>/^Completed (scan|manual sort)/.test(x.description)),todayCount=()=>sortEntries().filter(x=>dayKey(x.date)===dayKey(Date.now())).length;
function streak(){const days=new Set(sortEntries().map(x=>dayKey(x.date)));let d=new Date();d.setHours(12,0,0,0);if(!days.has(dayKey(d)))d.setDate(d.getDate()-1);let n=0;while(days.has(dayKey(d))){n++;d.setDate(d.getDate()-1)}return n}
function toast(s){const el=$('#toast');if(!el)return;el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
function shell(content){$('#app').innerHTML=`<header class="topbar"><a class="brand" href="#" data-action="home"><span class="brand-mark">♻️</span>SortWise</a><button class="coin-pill" data-tab="rewards">🪙 <b>${balance()}</b><small>pts</small></button></header><main>${content}</main><nav class="bottom-nav">${[['scan','📷','Scan'],['rewards','🎁','Rewards'],['games','🎮','Games'],['me','🙂','Me']].map(([id,icon,label])=>`<button data-tab="${id}" class="nav-tab ${tab===id?'active':''}"><span>${icon}</span>${label}</button>`).join('')}</nav><div id="toast" class="toast" role="status"></div>${modalHTML()}`}
function originalScanHome(){return `<section class="home-hero"><div class="eyebrow">SUSS · SORT SMART</div><h1>Finished eating?</h1><p>We’ll help you sort your tray before you go.</p><button class="primary huge full" data-action="pick">📷　Scan my tray</button><button class="text-link" data-action="gallery">Choose a photo from gallery</button><button class="text-link" data-action="manual">No camera? Sort manually →</button></section><section class="home-note">🌱 <span><b>Small steps, cleaner compost.</b><br>Keep liquids, packaging and food scraps apart.</span></section><input id="photo" type="file" accept="image/*" capture="environment" hidden><input id="gallery" type="file" accept="image/*" hidden>`}
function originalFlowHTML(){switch(flow.screen){case'preview':return `<section class="flow"><button class="back-link" data-action="cancel">← Back</button><div class="eyebrow">YOUR TRAY</div><h1>Does this look right?</h1><img class="tray-photo" src="${flow.image}" alt="Tray photo preview"><div class="stack"><button class="primary" data-action="scan">Scan this</button><button class="secondary" data-action="pick">Retake / choose another</button></div></section>`;case'loading':return `<section class="flow loading"><img class="tray-photo" src="${flow.image}" alt="Tray"><div class="scanline"></div><div class="loading-copy"><span class="spinner"></span><h2>Looking at your tray...</h2><p>Checking what can be composted</p></div></section>`;case'manual':return manualPage();case'items':return itemsPage();case'edit':return editPage();case'steps':return stepPage();case'success':return successPage();case'error':return `<section class="flow"><div class="error-icon">📶</div><h1>Couldn’t scan right now</h1><p>${esc(flow.message)}</p><div class="stack"><button class="primary" data-action="retry">Try again</button><button class="secondary" data-action="manual">Sort manually</button></div></section>`;case'not-tray':return `<section class="flow"><div class="error-icon">🔎</div><h1>That doesn’t look like a meal tray.</h1><p>Try again from directly above.</p><button class="primary full" data-action="pick">Retake photo</button></section>`;case'game-intro':return gameIntro();case'game':return gamePlay();case'game-result':return gameResult();default:return ''}}
function emoji(name,bin){return ITEMS.find(i=>name.toLowerCase().includes(i.name.toLowerCase())||i.name.toLowerCase().includes(name.toLowerCase()))?.emoji||BINS[bin]?.emoji||'🔎'}
function itemsPage(){return `<section class="flow"><button class="back-link" data-action="cancel">← Scan home</button><div class="eyebrow">TRAY CHECK</div><h1>Here’s what’s on your tray</h1><p class="muted">Check the detected items; edit anything that looks off.</p>${flow.tip?`<div class="tip-box">💡 ${esc(flow.tip)}</div>`:''}<div class="detected-list">${flow.items.length?flow.items.map(x=>`<article class="detected-item"><span>${esc(x.emoji||emoji(x.name,x.bin))}</span><div><b>${esc(x.name)}</b><small class="bin-tag" style="--bin:${BINS[x.bin].color}">${BINS[x.bin].name}</small>${x.confidence==='low'||x.confidence==='medium'?`<small class="low-confidence">${x.confidence==='low'?'Double-check this one':'Check this one'}</small>`:''}${x.reason?`<small class="detection-reason">${esc(x.reason)}</small>`:''}</div></article>`).join(''):'<p>No items selected yet. Edit to add what is on your tray.</p>'}</div><div class="stack"><button class="primary" data-action="begin">Show me how to sort</button><button class="secondary" data-action="edit">Edit items</button></div></section>`}
function editPage(){const selected=new Set(flow.items.map(x=>x.name.toLowerCase()));return `<section class="flow"><button class="back-link" data-action="items">← Back to tray</button><div class="eyebrow">EDIT TRAY ITEMS</div><h1>Add or remove items</h1><p class="muted">Tap everything you can see.</p><div class="catalog-grid">${ITEMS.map((x,i)=>`<button class="catalog-item ${selected.has(x.name.toLowerCase())||[...selected].some(n=>n.includes(x.name.toLowerCase()))?'selected':''}" data-action="toggle-edit" data-i="${i}"><span>${x.emoji}</span>${esc(x.name)}</button>`).join('')}</div><button class="primary full" data-action="save-edit">Update sorting steps</button></section>`}
function buildSteps(items){const has=b=>items.some(x=>x.bin===b),steps=[],table=[];if(has('general_waste'))table.push('set aside packaging and utensils');if(has('recyclables'))table.push('keep clean bottles and cans separate');if(has('food_waste'))table.push('keep food scraps together on your tray');if(table.length)steps.push({where:'table',bin:'none',emoji:'🍽️',instruction:`At your table, ${table.join(', and ')}.`});for(const [bin,emojiText,text] of [['drain','💧','Pour all soup and drinks into the drain first.'],['general_waste','🗑️','Put cutlery, packets and wrappers in General Waste.'],['recyclables','♻️','Place only clean bottles and cans in Recyclables.'],['food_waste','🥬','Scrape the food scraps into Food Waste last.']])if(has(bin))steps.push({where:'bin',bin,emoji:emojiText,instruction:text});if(!steps.length)steps.push({where:'table',bin:'none',emoji:'✅',instruction:'Check each item on your tray before sorting it.'});return steps}
function stepPage(){const x=flow.steps[flow.i],color=x.bin==='none'?'#25884a':BINS[x.bin].color;return `<section class="flow step-screen"><button class="back-link" data-action="step-back">← ${flow.i?'Previous step':'Tray items'}</button><div class="step-progress"><b>Step ${flow.i+1} of ${flow.steps.length}</b><div class="progress"><i style="width:${(flow.i+1)/flow.steps.length*100}%"></i></div></div><article class="big-step" style="--bin:${color}"><small>${x.where==='table'?'AT YOUR TABLE':'AT THE BIN'}</small><span>${x.emoji}</span><h1>${esc(x.instruction)}</h1><b>${x.bin==='none'?'Get ready':`${BINS[x.bin].emoji} ${BINS[x.bin].name}`}</b></article><button class="primary huge full" data-action="step-done">${flow.i===flow.steps.length-1?'Finish sorting':'Done ✓'}</button></section>`}
function successPage(){const next=[50,120,200,300].find(n=>n>balance())||300;return `<section class="flow success"><div class="confetti">${Array.from({length:18},(_,i)=>`<i style="--i:${i};left:${(i*37)%100}%"></i>`).join('')}</div><span class="success-icon">🌟</span><div class="eyebrow">SORT COMPLETE</div><h1>Nice work!</h1><div class="earned">+${flow.earned} points</div><p>Your balance is <b>🪙 ${balance()} pts</b></p>${flow.maxed?'<div class="tip-box">Daily sorting points maxed out — come back tomorrow! Your sort still counts.</div>':''}<div class="reward-progress"><b>${Math.max(0,next-balance())} more points to your next reward</b><div class="progress"><i style="width:${Math.min(100,balance()/next*100)}%"></i></div><small>${next===50?'$0.30 drink discount':next===120?'Free drink':next===200?'$1 meal discount':'Free meal'}</small></div><div class="stack"><button class="primary" data-tab="rewards">See rewards</button><button class="secondary" data-action="cancel">Done</button></div></section>`}
function weekly(){const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return d}),vals=days.map(d=>ledger.filter(x=>dayKey(x.date)===dayKey(d)&&x.points>0).reduce((n,x)=>n+x.points,0)),max=Math.max(10,...vals);return `<div class="weekly">${days.map((d,i)=>`<div><b>${vals[i]||''}</b><i style="height:${Math.max(4,vals[i]/max*100)}%"></i><small>${d.toLocaleDateString([],{weekday:'short'})}</small></div>`).join('')}</div>`}
function qr(code){if(typeof qrcode!=='function')return `<div class="qr-fallback" role="img" aria-label="Voucher code ${esc(code)}">${esc(code)}</div>`;const image=qrcode(0,'M');image.addData(`SORTWISE-VOUCHER:${code}`);image.make();return `<div class="qr">${image.createSvgTag({cellSize:5,margin:4,scalable:true})}</div>`}
document.addEventListener('input',e=>{if(!e.target.matches('.friend-search'))return;const q=e.target.value.trim().toLowerCase();document.querySelectorAll('[data-search-row]').forEach(row=>row.hidden=!row.dataset.searchRow.includes(q))});
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;if(el.classList.contains('backdrop')&&e.target!==el)return;
if(a==='redeem'){const cost=Number(el.dataset.cost),r=[[50,'$0.30 off your next drink'],[120,'Free drink (up to $2)'],[200,'$1 off any meal'],[300,'Free meal (up to $5)']].find(x=>x[0]===cost);if(r&&balance()>=cost){e.stopImmediatePropagation();modal={kind:'claim-warning',cost,title:r[1]};render()}return}
if(a==='claim-voucher-ok'){e.stopImmediatePropagation();if(!modal||modal.kind!=='claim-warning')return;const m=modal;add(`Redeemed · ${m.title}`,-m.cost);vouchers.unshift({title:m.title,code:`SW-${Math.random().toString(36).slice(2,6).toUpperCase()}`,outlet,expires:Date.now()+900000,used:false});modal={kind:'voucher'};render();toast('Reward claimed · show this QR to the cashier');return}
if(a==='add-friend'){e.stopImmediatePropagation();modal={kind:'add-friend'};render();return}if(a==='add-this-friend'){e.stopImmediatePropagation();const f=INVITABLE.find(x=>x.name===el.dataset.name);if(f&&!allFriends().some(x=>x.name===f.name))addedFriends.push({...f});modal=null;render();toast(`${el.dataset.name} added as a friend`);return}if(a==='share-invite'){e.stopImmediatePropagation();toast('Invite link copied!');return}
if(a==='challenge-friend-picker'){e.stopImmediatePropagation();modal={kind:'friend-picker'};render();return}if(a==='start-challenge'){e.stopImmediatePropagation();const f=allFriends().find(x=>x.name===el.dataset.name);if(f)startChallenge(f,mockSequence());return}if(a==='play-incoming'){e.stopImmediatePropagation();const c=pendingChallenges.find(x=>x.id===el.dataset.id);if(c)startChallenge(c.friend,c.sequence,true,{id:c.id,score:c.score});return}
if(a==='challenge-answer'){e.stopImmediatePropagation();const item=ITEMS[challenge.sequence[challenge.index]];challenge.score=el.dataset.bin===item.bin?challenge.score+10:Math.max(0,challenge.score-5);challenge.index++;if(challenge.index>=15)finishChallenge();else render();return}if(a==='challenge-quit'){e.stopImmediatePropagation();challenge=null;flow=null;tab='games';render();return}if(a==='challenge-back'){e.stopImmediatePropagation();challenge=null;flow=null;tab='games';render();return}if(a==='challenge-rematch'){e.stopImmediatePropagation();const previous=challenge;challenge={...previous,index:0,score:0,friendScore:null,bonus:0,incoming:false};flow={screen:'challenge-play'};render();return}
if(a==='leader-tab'){e.stopImmediatePropagation();leaderboardScope=el.dataset.scope;render();return}
if(a==='table-challenge'||a==='start-table'){e.stopImmediatePropagation();startTable();return}if(a==='table-sort'){e.stopImmediatePropagation();modal={kind:'table-sort-picker'};render();return}if(a==='table-scan'){e.stopImmediatePropagation();modal=null;setTab('scan');setTimeout(()=>$('#photo')?.click(),0);return}if(a==='table-manual'){e.stopImmediatePropagation();modal=null;flow={kind:'manual',screen:'manual',selected:new Set};shell(manualPage());return}if(a==='table-cancel'){e.stopImmediatePropagation();tab='scan';render();return}
if(a==='pick-buddy'){e.stopImmediatePropagation();modal={kind:'buddy-picker'};render();return}if(a==='set-buddy'){e.stopImmediatePropagation();streakBuddy=el.dataset.name;modal=null;render();toast(`${streakBuddy} is your streak buddy!`);return}if(a==='nudge'){e.stopImmediatePropagation();toast(`Nudge sent to ${streakBuddy} 👋`);return}
},true);

function challengePlayPage(){const item=ITEMS[challenge.sequence[challenge.index]];return `<section class="flow challenge-play"><div class="game-top"><button class="back-link" data-action="challenge-quit">✕ Quit</button><b>Item ${challenge.index+1} of 15</b><b>Score ${challenge.score}</b></div><div class="rush-item"><span>${item.emoji}</span><h1>${esc(item.name)}</h1></div><p>Which bin?</p><div class="bin-buttons">${Object.entries(BINS).map(([id,b])=>`<button style="--bin:${b.color}" data-action="challenge-answer" data-bin="${id}"><span>${b.emoji}</span>${b.name}</button>`).join('')}</div></section>`}
function challengeWaitPage(){return `<section class="flow challenge-wait"><div class="spinner"></div><div class="eyebrow">CHALLENGE SENT</div><h1>Nice round!</h1><p>Waiting for ${esc(challenge.friend.name)} to play the same 15 items...</p><div class="loading-card">${challenge.friend.avatar}<b>${esc(challenge.friend.name)}</b><span>Playing now…</span></div></section>`}
function challengeResultPage(){const won=challenge.score>challenge.friendScore,tie=challenge.score===challenge.friendScore;return `<section class="flow challenge-result"><div class="eyebrow">HEAD-TO-HEAD</div><h1>${won?'You win! 🏆':tie?'So close! Rematch?':`${esc(challenge.friend.name)} wins this round`}</h1><div class="versus"><article class="${won?'winner':''}"><span>🙂</span><b>${esc(nickname)}</b><strong>${challenge.score}</strong></article><b class="vs">VS</b><article class="${!won&&!tie?'winner':''}"><span>${challenge.friend.avatar}</span><b>${esc(challenge.friend.name)}</b><strong>${challenge.friendScore}</strong></article></div>${won?`<div class="challenge-bonus">${challenge.bonus?`+${challenge.bonus} bonus points added`:'Game points maxed for today'}</div>`:`<p class="friendly-line">${tie?'A perfect match. Want another round?':'So close! Rematch?'}</p>`}<div class="stack"><button class="primary" data-action="challenge-rematch">Rematch</button><button class="secondary" data-action="challenge-back">Back</button></div></section>`}
function awardChallengeWin(){const room=Math.max(0,20-todayGames()),points=Math.min(5,room);challenge.bonus=points;if(points)add(`Games · Challenge win · ${challenge.friend.name}`,points);if(!points)toast('Game points maxed for today');else toast(`Challenge win! +${points} points`)}
function finishChallenge(){if(challenge.incoming){challenge.friendScore=challenge.targetScore;challenge.screen='result';if(challenge.score>challenge.friendScore)awardChallengeWin();const pending=pendingChallenges.find(x=>x.id===challenge.id);if(pending)pending.pending=false;flow.screen='challenge-result';render();return}flow.screen='challenge-wait';render();setTimeout(()=>{if(!challenge)return;const delta=Math.floor(Math.random()*81)-40;challenge.friendScore=Math.max(0,challenge.score+delta);toast(`${challenge.friend.name} played your challenge! Score: ${challenge.friendScore}`);if(challenge.score>challenge.friendScore)awardChallengeWin();flow.screen='challenge-result';render()},5000)}
function startChallenge(friend,sequence,incoming=false,meta={}){challenge={friend,sequence:[...sequence],index:0,score:0,friendScore:null,incoming,id:meta.id||null,targetScore:meta.score||0};modal=null;game=null;flow={screen:'challenge-play'};render()}
function startTable(){tableTimers.forEach(clearTimeout);const chosen=[...allFriends()].sort(()=>Math.random()-.5).slice(0,3);tableChallenge={people:[{name:nickname,avatar:'🙂',sorted:false,isUser:true},...chosen.map(x=>({name:x.name,avatar:x.avatar,sorted:false}))],complete:false,rewarded:false,userSorted:false};tab='table';modal=null;render();chosen.forEach((f,i)=>tableTimers.push(setTimeout(()=>{if(!tableChallenge)return;const person=tableChallenge.people.find(x=>x.name===f.name);if(person)person.sorted=true;checkTableComplete();if(tab==='table'&&!flow)render()},3000*(i+1))))}
function checkTableComplete(){if(!tableChallenge||tableChallenge.complete||!tableChallenge.userSorted||tableChallenge.people.some(x=>!x.sorted))return;tableChallenge.complete=true;if(!tableBonusToday()){add('Table challenge bonus',10);tableChallenge.rewarded=true;toast('Whole table sorted! +10 bonus points 🎉')}else{tableChallenge.rewarded=false;toast('Whole table sorted! 🎉')}if((!flow&&tab==='table')||flow?.screen==='success')render()}
function tableSortChoice(){modal={kind:'table-sort-picker'};render()}
function challengeItems(){return challenge.sequence.map(i=>ITEMS[i])}
function rankedScope(){return mockBoard('friends').findIndex(x=>x.isUser)+1}

function completeSort(){const oldRank=rankedScope();originalCompleteSort();if(tableChallenge){tableChallenge.userSorted=true;tableChallenge.people[0].sorted=true;checkTableComplete()}const newRank=rankedScope();if(newRank<oldRank){toast(`You moved up to #${newRank}! 🎉`);render()}}

function scanHome(){return originalScanHome().replace('<button class="text-link" data-action="manual">No camera? Sort manually →</button>','<button class="text-link" data-action="manual">No camera? Sort manually →</button><button class="text-link" data-action="quick-food-sort">🥬 Quick food waste sort</button><button class="secondary full table-cta" data-action="table-challenge">🍽️ Table challenge</button><button class="quest-shortcut" data-action="reel-quest">🎬 Earn 10 points · Food waste Reel</button>')}
function voucherSection(){return `<section class="section"><h2>My vouchers</h2>${vouchers.length?vouchers.map((v,i)=>`<article class="voucher"><div class="voucher-head"><b>${esc(v.title)}</b><span>${v.used?'Used':Date.now()>v.expires?'Expired':'Active'}</span></div><p>${esc(v.outlet)} · ${esc(v.code)}</p>${qr(v.code)}${!v.used&&Date.now()<v.expires?`<small class="countdown" data-expires="${v.expires}"></small><button class="primary full" data-action="voucher-used" data-i="${i}">Mark as used</button>`:''}</article>`).join(''):'<div class="empty-card">🎟️<p>Redeemed vouchers will show here.</p></div>'}</section>`}
function rewardsPage(){const costs=[50,120,200,300],next=costs.find(x=>x>balance()),rew=[[50,'$0.30 off your next drink','Save on your next refreshment'],[120,'Free drink','Any drink up to $2'],[200,'$1 off any meal','Save on your next meal'],[300,'Free meal','Any meal up to $5']];return `<section class="page-heading"><div class="eyebrow">YOUR POINTS</div><h1>Rewards</h1><p>Make your good habits count.</p></section><div class="balance-card">🪙 <b>${balance()} points</b><small>Keep sorting to unlock rewards</small></div><section class="ladder"><h2>Reward progress</h2><div class="ladder-track"><i style="width:${Math.min(100,balance()/3)}%"></i><b style="left:${Math.min(100,balance()/3)}%">${balance()}</b>${costs.map((x,i)=>`<span class="milestone ${balance()>=x?'reached':''} ${x===next?'next':''}" style="left:${x/3}%"><i>${balance()>=x?'✓':i+1}</i><small>${x}</small></span>`).join('')}</div><p>${next?`${next-balance()} points to go`:'All rewards unlocked 🎉'}</p></section><section class="section"><h2>Choose a reward</h2><div class="reward-list">${rew.map(([cost,title,desc])=>`<article class="reward"><span class="cost">${cost}<small>pts</small></span><div><b>${title}</b><small>${desc}</small></div><button class="redeem" data-action="redeem" data-cost="${cost}" ${balance()<cost?'disabled':''}>${balance()<cost?`Need ${cost-balance()} more`:'Redeem'}</button></article>`).join('')}</div></section>${voucherSection()}<section class="section"><div class="section-head"><h2>Points history</h2><b>Total ${balance()}</b></div><div class="history">${[...ledger].sort((a,b)=>new Date(b.date)-new Date(a.date)).map(e=>{const idx=ledger.findIndex(x=>x.id===e.id),run=ledger.slice(0,idx+1).reduce((n,x)=>n+x.points,0);return `<div class="history-row"><span><b>${esc(e.description)}</b><small>${new Date(e.date).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></span><strong class="${e.points>0?'positive':'negative'}">${e.points>0?'+':''}${e.points}</strong><small>${run} pts</small></div>`}).join('')}</div><div class="history-total">Ledger balance <b>${balance()} points</b></div></section><section class="section"><h2>Last 7 days</h2><p class="muted">Points earned</p>${weekly()}</section>`}
const todayGames=()=>ledger.filter(x=>x.description.startsWith('Games ·')&&dayKey(x.date)===dayKey(Date.now())).reduce((n,x)=>n+x.points,0);
function originalGamesPage(){return `<section class="page-heading"><div class="eyebrow">PLAY & LEARN</div><h1>Games</h1><p>Quick rounds, better sorting instincts.</p></section><div class="daily-cap">🎮 ${Math.max(0,20-todayGames())} game points left today</div><div class="game-list">${[['rush','⚡','Sort Rush','Sort each item into the right bin.','30 sec'],['spot','🕵️','Spot the Contaminant','Find what doesn’t belong in food waste.','5 rounds'],['quiz','🧠','Sort Quiz','Test your SUSS sorting knowledge.','5 questions']].map(([id,icon,name,desc,time])=>`<article class="game-card"><span>${icon}</span><div><h2>${name}</h2><p>${desc}</p><small>Best: ${best[id]} pts · ${time}</small></div><button class="primary" data-action="game-intro" data-game="${id}">Play</button></article>`).join('')}</div>`}
function badge(name){const sorts=totalSorts;return name==='First Scan'?ledger.some(x=>x.description.toLowerCase().includes('first scan bonus')):name==='3-Day Streak'?streak()>=3||ledger.some(x=>x.description.includes('3-day streak')):name==='7-Day Streak'?streak()>=7||ledger.some(x=>x.description.includes('7-day streak')):name==='Sort Rush 200+'?best.rush>=200:sorts>=10}
function originalMePage(){const sorts=totalSorts,badges=['First Scan','3-Day Streak','7-Day Streak','Sort Rush 200+','10 Sorts'];return `<section class="page-heading"><div class="eyebrow">YOUR IMPACT</div><h1>Me</h1></section><article class="profile"><span>🙂</span><div><b>${esc(nickname)}</b><small>SUSS diner</small></div><button class="secondary compact" data-action="name">Edit</button></article><div class="stats"><article>🔥<b>${streak()} days</b><small>Current streak</small></article><article>✅<b>${sorts}</b><small>Total sorts</small></article><article>🌱<b>${(sorts*.3).toFixed(1)} kg</b><small>Kept clean for composting</small></article></div><small class="assumption">Estimate assumes 0.3 kg food waste per successfully sorted tray.</small><section class="section"><h2>Badges</h2><div class="badges">${badges.map((n,i)=>`<div class="badge ${badge(n)?'earned':''}"><span>${['🌱','🔥','🏆','⚡','🥇'][i]}</span><b>${n}</b><small>${badge(n)?'Earned':'Keep going'}</small></div>`).join('')}</div></section><section class="section"><h2>Settings</h2><label class="setting"><span><b>Demo mode</b><small>Sample tray scans for showcase Wi-Fi</small></span><input type="checkbox" data-action="demo" ${demo?'checked':''}></label><div class="setting"><span><b>Outlet</b><small>${esc(outlet)}</small></span><button class="secondary compact" data-action="outlet">Change</button></div><button class="secondary full reset" data-action="reset">Reset demo data</button></section>`}
function originalModalHTML(){if(!modal)return '';if(modal.kind==='redeem')return `<div class="backdrop" data-action="close"><section class="sheet"><div class="grab"></div><h2>Redeem this reward?</h2><p>Use <b>${modal.cost} points</b> for ${esc(modal.title)}?</p><div class="balance-change">Your balance <b>${balance()} → ${balance()-modal.cost}</b></div><button class="primary full" data-action="confirm">Confirm</button><button class="secondary full" data-action="close">Cancel</button></section></div>`;if(modal.kind==='voucher'){const v=vouchers[0];return `<div class="backdrop"><section class="voucher-modal"><button class="close" data-action="close">✕</button><div class="eyebrow">YOUR VOUCHER</div><h2>${esc(v.title)}</h2><b class="code">${v.code}</b>${qr(v.code)}<p>${esc(v.outlet)}</p><b>Show this to the cashier.</b><small class="countdown" data-expires="${v.expires}"></small><button class="primary full" data-action="voucher-used" data-i="0">Mark as used</button></section></div>`}return ''}
function gameIntro(){const info={rush:['⚡','Sort Rush','Tap one of the four bins for each item. Correct answers score points; the round lasts 30 seconds.'],spot:['🕵️','Spot the Contaminant','Tap the 2–3 items that do not belong in food waste. Five quick rounds.'],quiz:['🧠','Sort Quiz','Answer five questions about the SUSS sorting rules.'] }[game.id];return `<section class="flow game-intro"><button class="back-link" data-action="games-home">← Games</button><span class="game-icon">${info[0]}</span><div class="eyebrow">QUICK GAME</div><h1>${info[1]}</h1><p>${info[2]}</p><b>🏆 Best score: ${best[game.id]}</b><button class="primary huge full" data-action="game-start">Start</button></section>`}
function gamePlay(){if(game.id==='rush')return `<section class="game-play"><div class="game-top"><button class="back-link" data-action="quit">✕ Quit</button><b id="timer">${game.seconds}s</b><b>Score ${game.score}</b></div><div class="rush-item ${game.shake?"shake":""}"><span>${game.item.emoji}</span><h1>${esc(game.item.name)}</h1>${game.combo>=2?'<small>🔥 Combo ready · next correct +20</small>':''}</div><p>Which bin?</p><div class="bin-buttons">${Object.entries(BINS).map(([id,b])=>`<button style="--bin:${b.color}" class="${game.flash===id?"flash-correct":""}" data-action="rush-answer" data-bin="${id}"><span>${b.emoji}</span>${b.name}</button>`).join('')}</div></section>`;if(game.id==='spot')return `<section class="game-play"><div class="game-top"><button class="back-link" data-action="quit">✕ Quit</button><b>Round ${game.round}/5</b><b>Score ${game.score}</b></div><h1>What doesn’t belong?</h1><p class="muted">Tap the items that should not go in food waste.</p><div class="spot-grid">${game.tiles.map((x,i)=>`<button class="spot-tile ${game.tapped.has(i)?'selected':''}" data-action="spot-toggle" data-i="${i}"><span>${x.emoji}</span>${esc(x.name)}</button>`).join('')}</div><button class="primary full" data-action="spot-check">Check answers</button></section>`;const q=game.questions[game.q];return `<section class="game-play"><div class="game-top"><button class="back-link" data-action="quit">✕ Quit</button><b>Question ${game.q+1}/5</b><b>Score ${game.score}</b></div><div class="progress"><i style="width:${(game.q+1)*20}%"></i></div><h1>${esc(q[0])}</h1><div class="quiz-options">${q[1].map((x,i)=>`<button class="quiz-option" data-action="quiz-answer" data-i="${i}" ${game.answered?'disabled':''}>${esc(x)}</button>`).join('')}</div>${game.answered?`<p class="explanation">${game.correct?'✅ Correct!':'💡'} ${esc(q[3])}</p><button class="primary full" data-action="quiz-next">${game.q===4?'See results':'Next question'}</button>`:''}</section>`}
function gameResult(){const points=Math.min(Math.floor(game.score/10),Math.max(0,20-todayGames()));return `<section class="flow game-result"><span class="success-icon">🎉</span><div class="eyebrow">ROUND COMPLETE</div><h1>${game.id==='rush'?'Sort Rush':game.id==='spot'?'Spot the Contaminant':'Sort Quiz'}</h1><div class="game-score">${game.score}<small>score</small></div><p>Best score: ${best[game.id]}</p><div class="earned">+${points} points</div>${todayGames()>=20?'<p>Game points maxed for today</p>':''}<button class="primary full" data-action="claim" data-points="${points}">Collect points</button><button class="secondary full" data-action="games-home">Back to games</button></section>`}
function baseRender(){if(flow)shell(flowHTML());else shell(tab==='scan'?scanHome():tab==='rewards'?rewardsPage():tab==='games'?gamesPage():mePage())}
function setTab(t){if(game?.timer)clearInterval(game.timer);game=null;challenge=null;tab=t;flow=null;modal=null;render();window.scrollTo(0,0)}
async function readPhoto(file){if(!file?.type.startsWith('image/'))throw Error('Choose a photo image to continue.');const url=URL.createObjectURL(file);try{const img=await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>no(Error('Could not open that photo.'));i.src=url});const scale=Math.min(1,1024/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);const ctx=c.getContext('2d');if(!ctx)throw Error('This browser could not prepare the photo.');ctx.drawImage(img,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.8)}finally{URL.revokeObjectURL(url)}}
async function scanPhoto(){flow.screen='loading';render();try{let r;if(demo){await new Promise(ok=>setTimeout(ok,2000));r=DEMOS[Math.floor(Math.random()*DEMOS.length)]}else{const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),15000);try{const res=await fetch('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:flow.image.split(',')[1]}),signal:ctl.signal});const data=await res.json().catch(()=>({}));if(!res.ok)throw Error(data.error||`Scan service error (${res.status})`);r=data}finally{clearTimeout(timer)}}if(typeof r.is_food_tray!=='boolean')throw Error('The scan returned an unreadable result.');if(!r.is_food_tray){flow.screen='not-tray';render();return}if(!Array.isArray(r.items))throw Error('The scan returned no item list.');flow.items=r.items.filter(x=>x&&x.name&&BINS[x.bin]).map(x=>({...x,emoji:x.emoji||emoji(x.name,x.bin)}));flow.tip=r.tip||'';flow.screen='items';render()}catch(e){flow.message=e.name==='AbortError'?'The scan took over 15 seconds. Try again, or sort manually.':e instanceof TypeError?'Could not reach the scan service. Check your connection, or sort manually.':e.message;flow.screen='error';render()}}
function originalCompleteSort(){totalSorts++;const wasToday=sortEntries().some(x=>dayKey(x.date)===dayKey(Date.now()));flow.maxed=todayCount()>=3;flow.earned=0;if(!flow.maxed){const pts=flow.kind==='scan'?15:10;add(flow.kind==='scan'?'Completed scan':'Completed manual sort',pts);flow.earned+=pts}if(flow.kind==='scan'&&!ledger.some(x=>x.description.toLowerCase().includes('first scan bonus'))){add('First scan bonus',20);flow.earned+=20}if(!wasToday&&!flow.maxed){const s=streak(),bonus=s===3?10:s>=7&&s%7===0?30:0;if(bonus){add(`${s}-day streak bonus`,bonus);flow.earned+=bonus}}flow.screen='success';render();if(flow.earned)toast(`🪙 +${flow.earned} points`)}
function startGame(){Object.assign(game,{score:0,combo:0,round:0,answered:false});if(game.id==='rush'){game.seconds=30;nextRush();game.timer=setInterval(()=>{game.seconds--;const t=$('#timer');if(t)t.textContent=`${game.seconds}s`;if(game.seconds<=0)endGame()},1000)}if(game.id==='spot')nextSpot();if(game.id==='quiz'){game.questions=[...QUESTIONS].sort(()=>Math.random()-.5).slice(0,5);game.q=0}flow={screen:'game'};render()}
function nextRush(){game.item=ITEMS[Math.floor(Math.random()*ITEMS.length)]}
function nextSpot(){game.round++;const wrong=ITEMS.filter(x=>x.bin!=='food_waste').sort(()=>Math.random()-.5).slice(0,2+Math.floor(Math.random()*2)),good=ITEMS.filter(x=>x.bin==='food_waste').sort(()=>Math.random()-.5).slice(0,8-wrong.length);game.tiles=[...wrong.map(x=>({...x,wrong:true})),...good.map(x=>({...x,wrong:false}))].sort(()=>Math.random()-.5);game.tapped=new Set()}
function endGame(){clearInterval(game.timer);game.timer=null;best[game.id]=Math.max(best[game.id],game.score);flow.screen='game-result';render()}
function resetDemo(){ledger=[{id:'a',date:offset(-3),description:'First scan bonus',points:20},{id:'b',date:offset(-3),description:'Completed scan',points:15},{id:'c',date:offset(-2),description:'Completed scan',points:15},{id:'d',date:offset(-1),description:'Completed scan',points:15},{id:'e',date:offset(-1),description:'3-day streak bonus',points:10},{id:'f',date:offset(0),description:'Games · Sort Rush',points:10}];vouchers=[];best={rush:0,spot:0,quiz:0};totalSorts=3;nickname='Eco-loop friend';demo=false;flow=null;modal=null;tab='me';render();toast('Demo data reset · 85 points')}
function onClick(e){const el=e.target.closest('[data-action],[data-tab]');if(!el)return;if(el.classList.contains('backdrop')&&e.target!==el)return;if(el.dataset.tab){setTab(el.dataset.tab);return}const a=el.dataset.action;
if(a==='home'){setTab('scan');return}if(a==='pick'||a==='gallery'){const id=a==='pick'?'photo':'gallery',input=$(`#${id}`);if(input)input.click();else{setTab('scan');setTimeout(()=>$(`#${id}`)?.click(),0)}return}if(a==='cancel'||a==='games-home'){if(game?.timer)clearInterval(game.timer);flow=null;game=null;modal=null;tab=a==='games-home'?'games':tab;render();return}
if(a==='manual'){flow={kind:'manual',screen:'manual',selected:new Set};shell(manualPage());return}if(a==='scan'){scanPhoto();return}if(a==='retry'){flow.screen='preview';scanPhoto();return}if(a==='begin'){flow.steps=buildSteps(flow.items);flow.i=0;flow.screen='steps';render();return}if(a==='edit'){flow.screen='edit';render();return}if(a==='items'){flow.screen='items';render();return}
if(a==='toggle-edit'){const x=ITEMS[Number(el.dataset.i)],arr=flow.items.filter(i=>!i.name.toLowerCase().includes(x.name.toLowerCase()));if(arr.length===flow.items.length)arr.push({...x,confidence:'high'});flow.items=arr;render();return}if(a==='save-edit'){flow.tip='';flow.screen='items';render();toast('Items updated');return}if(a==='step-back'){if(flow.i>0)flow.i--;else flow.screen=flow.kind==='manual'?'manual':'items';render();return}if(a==='step-done'){if(flow.i<flow.steps.length-1){flow.i++;render()}else completeSort();return}
if(a==='manual-toggle'){const i=Number(el.dataset.i);flow.selected.has(i)?flow.selected.delete(i):flow.selected.add(i);shell(manualPage());return}if(a==='manual-continue'){if(!flow.selected.size)return;flow.items=[...flow.selected].map(i=>({...ITEMS[i],confidence:'high'}));flow.steps=buildSteps(flow.items);flow.i=0;flow.screen='steps';render();return}
if(a==='redeem'){const cost=Number(el.dataset.cost),r=[[50,'$0.30 off your next drink'],[120,'Free drink (up to $2)'],[200,'$1 off any meal'],[300,'Free meal (up to $5)']].find(x=>x[0]===cost);if(r&&balance()>=cost){modal={kind:'redeem',cost,title:r[1]};render()}return}if(a==='close'){modal=null;render();return}if(a==='confirm'){const m=modal;add(`Redeemed · ${m.title}`,-m.cost);vouchers.unshift({title:m.title,code:`SW-${Math.random().toString(36).slice(2,6).toUpperCase()}`,outlet,expires:Date.now()+900000,used:false});modal={kind:'voucher'};render();toast('Reward redeemed');return}if(a==='voucher-used'){const v=vouchers[Number(el.dataset.i)];if(v){v.used=true;modal=null;render();toast('Voucher marked as used ✓')}return}
if(a==='name'){const name=prompt('What should we call you?',nickname);if(name){nickname=name;render()}return}if(a==='outlet'){const n=prompt('Outlet name',outlet);if(n?.trim()){outlet=n.trim();render();toast('Outlet updated')}return}if(a==='reset'){if(confirm('Reset points, vouchers and game scores to the demo data?'))resetDemo();return}
if(a==='game-intro'){game={id:el.dataset.game};flow={screen:'game-intro'};render();return}if(a==='game-start'){startGame();return}if(a==='quit'){clearInterval(game.timer);game=null;flow=null;tab='games';render();return}if(a==='rush-answer'){const ok=el.dataset.bin===game.item.bin;if(ok){const pts=game.combo>=3?20:10;game.score+=pts;game.combo=pts===20?0:game.combo+1;game.flash="";game.shake=false;toast(`✅ +${pts}`)}else{game.score=Math.max(0,game.score-5);game.combo=0;game.flash=game.item.bin;game.shake=true;toast(`Try ${BINS[game.item.bin].name}`)}nextRush();render();if(game.flash)setTimeout(()=>{if(game?.flash){game.flash="";game.shake=false;render()}},650);return}
if(a==='spot-toggle'){const i=Number(el.dataset.i);game.tapped.has(i)?game.tapped.delete(i):game.tapped.add(i);render();return}if(a==='spot-check'){let hits=0;game.tiles.forEach((x,i)=>{if(x.wrong&&game.tapped.has(i))hits++;else if(!x.wrong&&game.tapped.has(i))game.score=Math.max(0,game.score-5)});game.score+=hits*10;if(game.round===5)endGame();else{nextSpot();render()}return}if(a==='quiz-answer'){const q=game.questions[game.q];game.correct=Number(el.dataset.i)===q[2];if(game.correct)game.score+=10;game.answered=true;render();return}if(a==='quiz-next'){if(game.q===4)endGame();else{game.q++;game.answered=false;render()}return}if(a==='claim'){const points=Number(el.dataset.points);if(points)add(`Games · ${game.id==='rush'?'Sort Rush':game.id==='spot'?'Spot the Contaminant':'Sort Quiz'}`,points);game=null;flow=null;tab='games';render();toast(points?`🪙 +${points} points`:'Game points maxed for today');return}}
function manualPage(){return `<section class="flow"><button class="back-link" data-action="cancel">← Back</button><div class="eyebrow">MANUAL SORT</div><h1>What’s on your tray?</h1><p class="muted">Tap all the items you need to sort.</p><div class="catalog-grid">${ITEMS.map((x,i)=>`<button class="catalog-item ${flow.selected.has(i)?'selected':''}" data-action="manual-toggle" data-i="${i}"><span>${x.emoji}</span>${esc(x.name)}</button>`).join('')}</div><div class="sticky-action"><small>${flow.selected.size} selected</small><button class="primary full" data-action="manual-continue" ${flow.selected.size?'':'disabled'}>Show me how to sort</button></div></section>`}
document.addEventListener('click',onClick);
document.addEventListener('change',e=>{if(e.target.id==='photo'||e.target.id==='gallery'){const f=e.target.files?.[0];if(f)readPhoto(f).then(image=>{flow={kind:'scan',screen:'preview',image};scanPhoto()}).catch(err=>toast(err.message));e.target.value=''}if(e.target.dataset.action==='demo'){demo=e.target.checked;toast(demo?'Demo scans are on':'Demo scans are off')}});
setInterval(()=>document.querySelectorAll('.countdown').forEach(el=>{const ms=Number(el.dataset.expires)-Date.now();el.textContent=ms<=0?'Expired':`Expires in ${Math.floor(ms/60000)}:${String(Math.floor(ms%60000/1000)).padStart(2,'0')}`}),1000);
// Friends, challenges and leaderboard use mock data only; no social data leaves this page.
const FRIENDS=[{name:'Ryan',avatar:'🦊',weekly:12,streak:6,rush:240},{name:'Mei',avatar:'🐼',weekly:10,streak:4,rush:180},{name:'Aisha',avatar:'🌻',weekly:9,streak:8,rush:210},{name:'Jun',avatar:'🐸',weekly:8,streak:3,rush:160},{name:'Priya',avatar:'🦋',weekly:7,streak:5,rush:220},{name:'Darren',avatar:'🐯',weekly:5,streak:2,rush:190}];
const INVITABLE=[['Nadia','🐨'],['Kai','🐙'],['Hana','🦄'],['Ethan','🐻'],['Lina','🐱'],['Noah','🐳'],['Sara','🦩'],['Arjun','🦁'],['Zoe','🐰'],['Amir','🐬']].map(([name,avatar],i)=>({name,avatar,weekly:3+i,streak:(i%6)+1,rush:120+i*13}));
const INCOMING=[{id:'in-mei',friend:FRIENDS[1],score:140,sequence:[0,6,12,1,7,13,2,8,14,3,9,0,4,10,5],pending:true},{id:'in-ryan',friend:FRIENDS[0],score:125,sequence:[6,1,11,2,8,12,3,9,13,4,10,14,5,7,0],pending:true}];
const FACULTY_MOCK=[['Ari','🦦',15,7,235],['Siti','🐝',13,5,180],['Ben','🐻‍❄️',11,4,205],['Chloe','🐣',10,9,260],['Irfan','🦈',8,3,195],['Leah','🐹',7,6,210],['Marcus','🦖',6,2,145],['Nina','🐰',5,5,190],['Yuki','🐱',4,4,225],['Rafi','🦉',3,3,170]].map(([name,avatar,weekly,streak,rush])=>({name,avatar,weekly,streak,rush}));
const CAMPUS_NAMES=[['Ari','🦦'],['Siti','🐝'],['Ben','🐻‍❄️'],['Chloe','🐣'],['Irfan','🦈'],['Leah','🐹'],['Marcus','🦖'],['Nina','🐰'],['Yuki','🐱'],['Rafi','🦉'],['Tess','🐢'],['Omar','🦝'],['Mika','🐨'],['Joel','🐧'],['Anya','🦊'],['Felix','🐸'],['Ivy','🦋'],['Sam','🐼'],['Mira','🐬'],['Dev','🦁'],['Elle','🐰'],['Hugo','🐻'],['Zara','🌻'],['Noel','🐙'],['Kira','🦩']];
let addedFriends=[],pendingChallenges=INCOMING,streakBuddy=null,leaderboardScope='friends',tableChallenge=null,challenge=null,tableTimers=[],reelUpload=null,reelQuestDay=null,quickFoodSelected=new Set([0,2,5]);
const allFriends=()=>[...FRIENDS,...addedFriends];
function recentSortCount(){const now=new Date(),monday=new Date(now);monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-(monday.getDay()+6)%7);return sortEntries().filter(x=>new Date(x.date)>=monday).length}
function resetCountdown(){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+((8-d.getDay())%7||7));const ms=d-Date.now();return `Resets in ${Math.floor(ms/86400000)} days ${Math.floor(ms%86400000/3600000)} hours`}
function tableBonusToday(){return ledger.some(x=>x.description==='Table challenge bonus'&&dayKey(x.date)===dayKey(Date.now()))}
function mockSequence(){return Array.from({length:15},()=>Math.floor(Math.random()*ITEMS.length))}
function mockBoard(scope){const self={name:nickname,avatar:'🙂',weekly:recentSortCount(),streak:streak(),rush:best.rush,isUser:true};let list;if(scope==='faculty')list=[...FACULTY_MOCK,self];else if(scope==='campus')list=[...CAMPUS_NAMES.map(([name,avatar],i)=>({name,avatar,weekly:28-i,streak:(i*3)%11+1,rush:310-i*7})),self];else list=[...allFriends(),self];return list.sort((a,b)=>b.weekly-a.weekly||a.name.localeCompare(b.name))}
function render(){if(flow){shell(flowHTML());return}shell(tab==='scan'?scanHome():tab==='rewards'?rewardsPage():tab==='games'?gamesPage():tab==='me'?mePage():tab==='leaderboard'?leaderboardPage():tab==='table'?tablePage():scanHome())}
function flowHTML(){if(flow?.screen==='quick-food')return quickFoodPage();if(flow?.screen==='challenge-play')return challengePlayPage();if(flow?.screen==='challenge-wait')return challengeWaitPage();if(flow?.screen==='challenge-result')return challengeResultPage();return originalFlowHTML()}
function quickFoodPage(){const foods=ITEMS.map((x,i)=>({...x,index:i})).filter(x=>x.bin==='food_waste');return `<section class="flow quick-food-page"><button class="back-link" data-action="cancel">← Scan home</button><div class="eyebrow">QUICK FOOD WASTE SORT</div><h1>What food scraps are left?</h1><p>Tap what you have, then follow one simple Food Waste step.</p><div class="catalog-grid">${foods.map(x=>`<button class="catalog-item ${quickFoodSelected.has(x.index)?'selected':''}" data-action="quick-food-toggle" data-i="${x.index}"><span>${x.emoji}</span>${esc(x.name)}</button>`).join('')}</div><button class="primary full" data-action="quick-food-continue" ${quickFoodSelected.size?'':'disabled'}>Show my easy sorting step</button><p class="muted quick-hint">Only select food scraps. Packaging, cutlery and liquids go to their own bins.</p></section>`}
function reelQuestPage(){const done=reelQuestDay===dayKey(Date.now());return `<div class="backdrop" data-action="close"><section class="sheet quest-sheet"><div class="grab"></div><div class="eyebrow">SIDE QUEST · +10 POINTS</div><h2>Make a quick food waste Reel</h2><p>Share why separating food scraps helps keep them compostable, and show how easy it is.</p><ol><li>Show food scraps from a meal</li><li>Keep liquids and packaging separate</li><li>Put scraps in Food Waste</li></ol><label class="quest-file">🎥 ${reelUpload?`Selected: ${esc(reelUpload.name)}`:'Choose your Reel video'}<input id="reel-upload" type="file" accept="video/*" hidden></label><small class="muted">This demo keeps your selected video on this device; it does not post to social media.</small>${done?'<div class="table-complete">Quest completed today ✓</div>':''}<button class="primary full" data-action="submit-reel-quest" ${!reelUpload||done?'disabled':''}>${done?'Completed today':'Submit Reel · earn 10 points'}</button><button class="secondary full" data-action="close">Maybe later</button></section></div>`}
function gamesPage(){const base=originalGamesPage().replace('<div class="daily-cap">','<button class="leaderboard-link" data-tab="leaderboard">🏆 Leaderboard</button><div class="daily-cap">');const pending=pendingChallenges.filter(x=>x.pending);return `${base}<button class="leaderboard-link" data-tab="leaderboard">🏆　Open leaderboard <span>View standings →</span></button><section class="section quest-card"><div class="eyebrow">SIDE QUEST · +10 POINTS</div><h2>Teach food waste sorting in a Reel</h2><p>Explain why separating food scraps matters, then show how easy it is.</p><button class="primary full" data-action="reel-quest">🎬 Start side quest</button></section><section class="section social-section"><div class="section-head"><h2>Friends</h2><button class="secondary compact" data-action="add-friend">＋ Add friend</button></div><div class="friend-mini-list">${allFriends().map(f=>`<article class="friend-mini"><span>${f.avatar}</span><b>${esc(f.name)}</b><small>🌿 ${f.weekly} trays · 🔥 ${f.streak}d · ⚡ ${f.rush}</small></article>`).join('')}</div></section><section class="section social-section"><div class="section-head"><h2>Challenges</h2>${pending.length?`<span class="red-badge">${pending.length}</span>`:''}</div><button class="primary full" data-action="challenge-friend-picker">Challenge a friend</button>${pending.length?pending.map(c=>`<article class="incoming-card"><div><span class="red-dot"></span><b>${esc(c.friend.name)} challenged you!</b><small>Score to beat: ${c.score}</small></div><button class="secondary compact" data-action="play-incoming" data-id="${c.id}">Play</button></article>`).join(''):'<p class="muted">No pending challenges. Pick a friend for a quick head-to-head.</p>'}</section>`}
function mePage(){let page=originalMePage();const buddy=streakBuddy?allFriends().find(f=>f.name===streakBuddy):null;const block=buddy?`<section class="section buddy-card"><div class="section-head"><h2>🔥 Streak buddy</h2><button class="text-link inline" data-action="pick-buddy">Change</button></div><div class="buddy-line"><span>🙂</span><b>You</b><strong>and</strong><span>${buddy.avatar}</span><b>${esc(buddy.name)}</b><em>${Math.min(streak(),buddy.streak)} days 🔥</em></div><button class="primary full" data-action="nudge">👋 Nudge ${esc(buddy.name)}</button></section>`:`<section class="section"><h2>Streak buddy</h2><p class="muted">Keep a streak going together.</p><button class="primary full" data-action="pick-buddy">Pick a friend</button></section>`;return page.replace('<section class="section"><h2>Badges</h2>',`${block}<button class="leaderboard-link" data-tab="leaderboard">🏆　Leaderboard <span>See where you stand →</span></button><section class="section"><h2>Badges</h2>`)}
function leaderboardPage(){const rows=mockBoard(leaderboardScope),rank=rows.findIndex(x=>x.isUser)+1,above=rows[rank-2],shown=rows.length>11&&rank>10?rows.slice(0,10):rows;return `<section class="leader-page"><button class="back-link" data-tab="games">← Games</button><div class="eyebrow">CLEAN TRAYS, GOOD HABITS</div><h1>Leaderboard</h1><div class="leader-tabs">${[['friends','Friends'],['faculty','My Faculty'],['campus','Campus']].map(([id,label])=>`<button class="${leaderboardScope===id?'selected':''}" data-action="leader-tab" data-scope="${id}">${label}</button>`).join('')}</div><p class="motivation">${rank===1?'You’re on top this week! 🏆':`You’re ${Math.max(1,above.weekly-rows[rank-1].weekly)} ${Math.max(1,above.weekly-rows[rank-1].weekly)===1?'tray':'trays'} behind ${esc(above.name)}. Sort one more tray today to catch up!`}</p><small class="reset-countdown">${resetCountdown()}</small><div class="podium">${rows.slice(0,3).map((x,i)=>`<div class="podium-person place-${i+1}"><span>${x.avatar}</span><b>${esc(x.name)}</b><small>${x.weekly} trays</small><strong>${i+1}</strong></div>`).join('')}</div><div class="leader-list">${shown.map((x,i)=>leaderRow(x,rows.findIndex(y=>y===x)+1)).join('')}</div>${rank>10?`<div class="pinned-user">${leaderRow(rows[rank-1],rank)}</div>`:''}<section class="section champions"><h2>Last week’s champions</h2><div>${[['Ryan','🦊',24],['Ari','🦦',22],['Mei','🐼',20]].map(([n,a,s],i)=>`<p><b>${i+1}. ${a} ${n}</b><span>${s} trays</span></p>`).join('')}</div></section><section class="section rush-champs"><h2>⚡ Sort Rush champions</h2>${[...allFriends(),{name:nickname,avatar:'🙂',rush:best.rush,isUser:true}].sort((a,b)=>b.rush-a.rush).slice(0,5).map((f,i)=>`<p><b>${i+1}. ${f.avatar} ${esc(f.name)}</b><span>${f.rush} pts</span></p>`).join('')}</section></section>`}
function leaderRow(f,rank){return `<article class="leader-row ${rank<=3?'top-'+rank:''} ${f.isUser?'user-row':''}"><b class="leader-rank">${rank}</b><span class="leader-avatar">${f.avatar}</span><b class="leader-name">${esc(f.name)}${f.isUser?' (you)':''}</b><span class="leader-score">${f.weekly} trays</span><small>🔥 ${f.streak}d</small></article>`}
function tablePage(){if(!tableChallenge)return `<section class="flow"><button class="back-link" data-tab="scan">← Scan</button><div class="eyebrow">SORT TOGETHER</div><h1>Table challenge</h1><p>Get your whole table to sort their trays.</p><button class="primary full" data-action="start-table">Start table challenge</button></section>`;return `<section class="flow table-page"><button class="back-link" data-tab="scan">← Scan</button><div class="eyebrow">TABLE CHALLENGE</div><h1>Let’s sort together</h1><p>Sort your tray while your friends get theirs ready.</p><div class="table-people">${tableChallenge.people.map(x=>`<article class="table-person"><span>${x.avatar}</span><b>${esc(x.name)}</b><small class="${x.sorted?'sorted':''}">${x.sorted?'Sorted ✓':'Waiting...'}</small></article>`).join('')}</div>${tableChallenge.complete?'<div class="table-complete">Whole table sorted! 🎉<small>+10 bonus points added to your ledger.</small></div>':''}<button class="primary full" data-action="table-sort">Sort my tray</button><button class="secondary full" data-action="table-cancel">Back to Scan</button></section>`}
function modalHTML(){if(modal?.kind==='reel-quest')return reelQuestPage();if(modal?.kind==='table-sort-picker')return `<div class="backdrop" data-action="close"><section class="sheet"><div class="grab"></div><h2>How would you like to sort?</h2><p>Your table challenge stays active while you sort.</p><button class="primary full" data-action="table-scan">Scan my tray</button><button class="secondary full" data-action="table-manual">Sort manually</button></section></div>`;if(modal?.kind==='table-sort-picker')return `<div class="backdrop" data-action="close"><section class="sheet"><div class="grab"></div><h2>How would you like to sort?</h2><p>Your table challenge stays active while you sort.</p><button class="primary full" data-action="table-scan">Scan my tray</button><button class="secondary full" data-action="table-manual">Sort manually</button></section></div>`;if(modal?.kind==='claim-warning')return `<div class="backdrop" data-action="close"><section class="sheet"><div class="grab"></div><div class="eyebrow">15-MINUTE VOUCHER</div><h2>Ready to claim?</h2><p>You must claim this reward within 15 minutes or the code will expire.</p><p><b>${esc(modal.title)}</b> · ${modal.cost} points</p><div class="balance-change">Your balance <b>${balance()} → ${balance()-modal.cost}</b></div><button class="primary full" data-action="claim-voucher-ok">OK, show my QR code</button><button class="secondary full" data-action="close">Cancel</button></section></div>`;if(modal?.kind==='add-friend')return `<div class="backdrop" data-action="close"><section class="sheet friend-sheet"><div class="grab"></div><h2>Add a friend</h2><input class="friend-search" type="search" placeholder="Search friends" aria-label="Search friends"><div class="friend-search-list">${INVITABLE.map(f=>`<div class="invite-row" data-search-row="${esc(f.name.toLowerCase())}"><span>${f.avatar}</span><b>${esc(f.name)}</b><button class="secondary compact" data-action="add-this-friend" data-name="${esc(f.name)}">Add</button></div>`).join('')}</div><button class="secondary full" data-action="share-invite">🔗 Share my invite link</button></section></div>`;if(modal?.kind==='friend-picker'||modal?.kind==='buddy-picker')return `<div class="backdrop" data-action="close"><section class="sheet friend-sheet"><div class="grab"></div><h2>${modal.kind==='buddy-picker'?'Choose your streak buddy':'Challenge a friend'}</h2>${allFriends().map(f=>`<button class="friend-choice" data-action="${modal.kind==='buddy-picker'?'set-buddy':'start-challenge'}" data-name="${esc(f.name)}"><span>${f.avatar}</span><b>${esc(f.name)}</b><small>${modal.kind==='buddy-picker'?`🔥 ${f.streak} days`:`${f.weekly} trays this week`}</small>→</button>`).join('')}</section></div>`;return originalModalHTML()}



render();

document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;if(a==='reel-quest'){e.stopImmediatePropagation();reelUpload=null;modal={kind:'reel-quest'};render()}else if(a==='submit-reel-quest'){e.stopImmediatePropagation();if(!reelUpload||reelQuestDay===dayKey(Date.now()))return;add('Side quest · Food waste Reel',10);reelQuestDay=dayKey(Date.now());modal={kind:'reel-quest'};render();toast('Side quest complete · +10 points')}else if(a==='quick-food-sort'){e.stopImmediatePropagation();quickFoodSelected=new Set([0,2,5]);flow={kind:'manual',screen:'quick-food'};render()}else if(a==='quick-food-toggle'){e.stopImmediatePropagation();const i=Number(el.dataset.i);quickFoodSelected.has(i)?quickFoodSelected.delete(i):quickFoodSelected.add(i);render()}else if(a==='quick-food-continue'){e.stopImmediatePropagation();if(!quickFoodSelected.size)return;flow={kind:'manual',items:[...quickFoodSelected].map(i=>({...ITEMS[i],confidence:'high'})),screen:'steps'};flow.steps=buildSteps(flow.items);flow.i=0;render()}},true);
document.addEventListener('change',e=>{if(e.target.id!=='reel-upload')return;const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('video/')){toast('Choose a video for your Reel');return}if(file.size>100*1024*1024){toast('Choose a video smaller than 100 MB');return}reelUpload={name:file.name,size:file.size};render()});
